
version: '3'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: segni
      POSTGRES_DB: birthday
    ports:
      - "5433:5432"
    labels:
      app: postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:segni@db:5432/birthday  # Use the service name 'db' in the URL
