version: '3'
services:
  web:
    build:
      context: ./ 
      dockerfile: Dockerfile  
    ports:
      - "8080:5000"  
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: segni
      POSTGRES_DB: Birthday
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
